/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const BusinessInfo = IDL.Record({
  'tagline' : IDL.Text,
  'name' : IDL.Text,
  'contactNumbers' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'removeProduct' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const BusinessInfo = IDL.Record({
    'tagline' : IDL.Text,
    'name' : IDL.Text,
    'contactNumbers' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'removeProduct' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };